version: '2'
services:
    HipsterHealth-app:
        image: HipsterHealth
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://HipsterHealth-postgresql:5432/HipsterHealth
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://HipsterHealth-elasticsearch:9200
        ports:
            - 8080:8080
    HipsterHealth-postgresql:
        extends:
            file: postgresql.yml
            service: HipsterHealth-postgresql
    HipsterHealth-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: HipsterHealth-elasticsearch
